### ISSUE TITLE
implement flexible HTML web interface using bootstrap

### ISSUE THREAD

**Issue by olivier-2018** [olivier-2018/SoftwareEngg_project#6]

**Comment by 4982** [comment]
What functions do we need on the site?

**Comment by olivier-2018** [comment]
sorry i did not see your msg..
I don't think we need anything fancy so the simple css formatting should be enough.

Having said that, we just discussed with Tipi that we should implement a user login feature so we will actually need a login/signup page in addition to the audio prediction.. I have created issue #23 for this.

Best is to use bootstrap with a navbar and there are tons of schemes available with HTML code we can use out of the box.

**Comment by olivier-2018** [comment]
closed with pull request #30 (app v2.0 release)
